export const functions = {
  "no-empty-function": "error",
  "no-loop-func": "error",
  "no-new-func": "error",
  "no-dupe-args": "error",
  "no-func-assign": "error",
  "max-lines-per-function": "off",
  "func-name-matching": "off",
  "function-paren-newline": "off",
  "prefer-arrow-callback": "off",
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "no-confusing-arrow": ["error", { "allowParens": true }],
  "arrow-parens": ["error", "always"],
  "func-names": ["error", "always"],
  "func-style": ["error", "declaration"],
  "arrow-body-style": ["error", "as-needed", { "requireReturnForObjectLiteral": true }],
};
