/* eslint sort-keys: "error" */

export const variable = {
  "block-scoped-var": "error",
  "init-declarations": "error",
  "no-const-assign": "error",
  "no-delete-var": "error",
  "no-empty-character-class": "error",
  "no-empty-pattern": "error",
  "no-floating-decimal": "error",
  "no-global-assign": "error",
  "no-implicit-coercion": "error",
  "no-inner-declarations": ["error", "both"],
  "no-label-var": "error",
  "no-magic-numbers": "off",
  "no-misleading-character-class": "error",
  "no-multi-assign": "error",
  "no-multi-str": "error",
  "no-redeclare": "error",
  "no-restricted-globals": "error",
  "no-restricted-syntax": "off",
  "no-self-assign": "error",
  "no-shadow": "off",
  "no-shadow-restricted-names": "error",
  "no-throw-literal": "error",
  "no-undef": "error",
  "no-undef-init": "error",
  "no-undefined": "error",
  "no-underscore-dangle": "error",
  "no-unsafe-negation": "error",
  "no-unused-expressions": ["error", { allowShortCircuit: true }],
  "no-unused-vars": "error",
  "no-useless-concat": "error",
  "no-useless-escape": "error",
  "no-var": "error",
  "no-void": "off",
  "no-with": "error",
  "one-var": ["error", "never"],
  "one-var-declaration-per-line": "error",
  "prefer-const": "error",
  radix: "error",
  "sort-vars": ["error", { ignoreCase: true }],
  "unicode-bom": "error",
  "use-isnan": "error",
  "vars-on-top": "error"
};
