export const variable = {
  "prefer-const": "error",
  "no-var": "error",
  "no-const-assign": "error",
  "no-undef": "error",
  "no-undefined": "error",
  "no-unused-vars": "error",
  "no-undef-init": "error",
  "no-delete-var": "error",
  "no-label-var": "error",
  "no-self-assign": "error",
  "init-declarations": "error",
  "no-restricted-globals": "error",
  "no-shadow": "off",
  "no-shadow-restricted-names": "error",
  "no-misleading-character-class": "error",
  "no-empty-character-class": "error",
  "use-isnan": "error",
  "no-unsafe-negation": "error",
  "sort-vars": ["error", { "ignoreCase": true }],
};
